# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_menu_button = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_menu_button.setFont(font)
        self.start_menu_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_menu_button.setObjectName("start_menu_button")
        self.horizontalLayout_2.addWidget(self.start_menu_button)
        self.score_text = QtWidgets.QLabel(self.widget_2)
        self.score_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.score_text.setObjectName("score_text")
        self.horizontalLayout_2.addWidget(self.score_text)
        self.score_label = QtWidgets.QLabel(self.widget_2)
        self.score_label.setObjectName("score_label")
        self.horizontalLayout_2.addWidget(self.score_label)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.timer_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timer_label.setFont(font)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.horizontalLayout_2.addWidget(self.timer_label)
        self.end_button = QtWidgets.QPushButton(self.widget_2)
        self.end_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.end_button.setObjectName("end_button")
        self.horizontalLayout_2.addWidget(self.end_button)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.prew = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prew.setFont(font)
        self.prew.setAlignment(QtCore.Qt.AlignCenter)
        self.prew.setObjectName("prew")
        self.horizontalLayout.addWidget(self.prew)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.next = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next.setFont(font)
        self.next.setAlignment(QtCore.Qt.AlignCenter)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_menu_button.setText(_translate("Form", "menu"))
        self.score_text.setText(_translate("Form", "Score: "))
        self.score_label.setText(_translate("Form", "00000"))
        self.pushButton.setText(_translate("Form", "start"))
        self.timer_label.setText(_translate("Form", "00:00"))
        self.end_button.setText(_translate("Form", "end"))
        self.prew.setText(_translate("Form", "TextLabel"))
        self.next.setText(_translate("Form", "TextLabel"))
